version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: always
    container_name: bars_db
    environment:
      POSTGRES_PASSWORD: bars12345
      POSTGRES_DB: BarsSupportDb
      POSTGRES_USER: bars
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bars -d BarsSupportDb"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:alpine
    container_name: bars_redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redisdata:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ./
      dockerfile: API/Dockerfile
    container_name: bars_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=BarsSupportDb;Username=bars;Password=bars12345
      - ConnectionStrings__Redis=redis:6379
      - JwtSettings__SecretKey=your-very-long-and-secure-secret-key-for-production-use-jb5k34jjk-45j354jkgnj-435tbkj45tk-45tjmbjkgnjkbk3-5n43bjgkb4jgbk-45ktkl3-5gtl4-43g54-g5gkn4kgn3
      - JwtSettings__Issuer=BarsPnz-Local
      - JwtSettings__Audience=BarsPnz-Local
      - Minio__Endpoint=minio-s3:9000
      - Minio__AccessKey=${MINIO_ROOT_USER}
      - Minio__SecretKey=${MINIO_ROOT_PASSWORD}
      - Minio__UseSSL=false
      - Minio__ExternalEndpoint=https://bars-1.tail686649.ts.net:8443/minio
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
  
  minio-s3:
    image: minio/minio
    container_name: minio-s3
    hostname: minio-s3
    restart: unless-stopped 
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_prod_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}       
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
  redisdata:
  minio_prod_data: